version: '3.4'

networks:
  default:
    driver: bridge
services:
  api:
    build: .
    networks:
      - default
    volumes:
      - ./app/:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    ports:
    - "5000:5000"
    container_name: fastapi-backend
    env_file:
      - .env
    links:
      - postgres


  vue:
    build:
      context: ./vue
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    container_name: vue-frontend
#    volumes:
#      - ./vue/ :/app/vue/
#      - /app/node_modules
    depends_on:
      - api

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
    - "5432:5432"
    container_name: postgres-database

  keycloak:
    image: jboss/keycloak
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    container_name: keyclaok-AuthN
    depends_on:
      - postgres